#' @title Grouped Number Summary for Numerical Data
#'
#' @description
#' \code{summBy()} generates summary statistics for numerical data
#' grouped by a categorical variable
#'
#' @param data dataset (optional)
#' @param ... a variable or variables. Colon separator \code{:} can be
#' used for multiple variables. See details.
#' @param by outcome variable for cross-tabulation
#' @param na.rm A logical value to specify missing values,
#' <NA> in the table
#' @param rnd specify rounding of numbers. See \code{\link{round}}.
#' @param print.table logical value to display formatted outputs
#'
#' @details
#'
#' \code{summBy()} produces grouped summary statistics, similar
#' to the outputs generated by
#' \code{summ()}.
#'
#'
#' \strong{ANNOTATIONS}
#'
#' \code{Obs.} = observation
#'
#' \code{NA.} = missing data
#'
#' \code{Mean} = Mean value
#'
#' \code{Std.Dev} = Standard deviation
#'
#' \code{Median} = Median value
#'
#' \code{Q1} = First quartile or percentile
#'
#' \code{Q3} = Third quartile or percentile
#'
#' \code{Normality} = P-value from Shapiro-Wilk Normality Test
#'
#' \strong{P-values from Statistical Tests}:
#'
#' \enumerate{
#'     \item Student's t-test if two levels
#'     \item Wilcoxon Rank Sum test if two levels (also known
#'     as Mann-Whitney test)
#'     \item ANOVA test if more than two levels
#'     \item Kruskal-Wallis test if more than two levels
#' }
#'
#' @return
#'
#' \code{data.frame}
#'
#' @import stats
#'
#' @seealso
#'
#' \code{\link{summ}}, \code{\link{tab}}, \code{\link{xtab}}
#'
#' @keywords
#'
#' number summary, statistics, descriptive, five number
#'
#' @author
#'
#' For any feedback, please contact \code{Myo Minn Oo} via:
#'
#' Email: \email{dr.myominnoo@@gmail.com}
#'
#' Website: \url{https://myominnoo.github.io/}
#'
#' @examples
#' \dontrun{
#'
#' ### GROUPED SUMMARY MEASURES
#' # using infert dataset
#' # one variable
#' summBy(infert, age, by = education)
#'
#' # multiple variables
#' summBy(infert, age, induced, case, by = education)
#' summBy(infert, age:pooled.stratum, by = education)
#'
#' # the whole dataset
#' summBy(infert, by = education)
#'
#'
#'
#'
#' ## IDRE UCLA Example 1
#' path <- "https://stats.idre.ucla.edu/stat/data/patient_pt1_stata_dm.dta"
#' hosp <- haven::read_dta(path)
#' codebook(hosp)
#'
#' # one variable
#' summBy(hosp, rbc, by = cancerstage)
#'
#' # multiple variables
#' summBy(hosp, tumorsize:age, lengthofstay, rbc:test2, by = cancerstage)
#'
#' # whole dataset
#' summBy(hosp, by = cancerstage) ## Error
#'
#' ## change to data.frame and then summBy
#' library(magrittr)
#' hosp %>% data.frame %>% summBy(by = cancerstage)
#'
#'
#'
#'
#'
#'
#' ## IDRE UCLA Example 2
#' path <- "https://stats.idre.ucla.edu/stat/stata/modules/kids.dta"
#' kids <- haven::read_dta(path)
#'
#' # display codebook
#' codebook(kids)
#'
#' # one variable
#' summBy(kids, age, by = sex)
#'
#' # multiple variables
#' summBy(kids, age, wt, by = sex)
#'
#' # the whole dataset
#' summBy(kids, by = sex) # Error
#'
#' library(magrittr)
#' kids %>% data.frame %>% summBy(by = sex)
#' }



#' @export
summBy <- function(data = NULL, ... , by = NULL,
                   na.rm = FALSE, rnd = 1,
                   print.table = TRUE)
{
  arguments <- as.list(match.call())[-1]
  if (!is.null(data)) {
    by <- eval(substitute(by), data)
  }
  nonX <- c("data", "by", "row.pct", "na.rm", "rnd", "print.table")
  x <- as.character(arguments[!(names(arguments) %in% nonX)])

  if (length(x) > 1) {
    x <- list()
  } else if (length(x) == 1 ) {
    if (any(grepl(":", x))) {
      x <- list()
    } else {
      x <- numeric()
    }
  } else {
    x <- data.frame()
  }

  if (is.null(by)) {
    stop(" >>> Specify 'by' variable <<< ")
  } else {
    UseMethod("summBy", x)
  }
}



#' @rdname summ
#' @export
summBy.default <- function( ... )
{
  stop(" >>> Data type is not supported. <<< ")
}

#' @rdname summ
#' @export
summBy.numeric <- function(data = NULL, x, by = NULL,
                           na.rm = FALSE, rnd = 1,
                           print.table = TRUE)
{
  arguments <- as.list(match.call())[-1]
  x.name <- deparse(substitute(x))
  by.name <- deparse(substitute(by))
  if (is.null(data)) {
    data <- data.frame(x, by)
    names(data) <- c(x.name, by.name)
  } else {
    data <- data.frame(data)
    x <- eval(substitute(x), data)
    by <- eval(substitute(by), data)
    data <- data[, c(x.name, by.name)]
  }

  na.rm <- ifelse(na.rm, "no", "ifany")
  t <- table(by, useNA = na.rm)
  lvl <- names(t)
  lvl[is.na(lvl)] <- "<NA>"

  f <- do.call(
    rbind,
    lapply(lvl, function(z) {
      if (z == "<NA>") {
        d <- data[is.na(by), x.name]
      } else {
        d <- data[by == z, x.name]
      }
      suppressWarnings(summ(NULL, d, rnd = rnd, print.table = FALSE))
    })
  )

  ## subset output show only Obs. to Q3
  display <- c("Obs.", "NA.", "Mean", "Std.Dev", "Median", "Q1", "Q3",
               "Normality")
  f <- f[, display]

  if (length(lvl) > 2) {
    pvalue <- tryCatch({
      suppressWarnings(summary(aov(x ~ by))[[1]][1,5])
    }, error = function(err) {
      return(NA)})
    pvalue.name <- 'ANOVA'

    pvalue <- c(
      pvalue,
      tryCatch({
        suppressWarnings(kruskal.test(x ~ by)$p.value)
      }, error = function(err) {
        return(NA)})
    )
    pvalue.name <- c(pvalue.name, 'K-Wallis')

  } else {
    pvalue <- tryCatch({
      suppressWarnings(t.test(x ~ by)$p.value)
    }, error = function(err) {
      return(NA)
    })
    pvalue.name <- 't-test'

    pvalue <- c(
      pvalue,
      tryCatch({
        suppressWarnings(wilcox.test(x ~ by)$p.value)
      }, error = function(err) {
        return(NA)})
    )
    pvalue.name <- c(pvalue.name, 'Wilcoxon')
  }
  pvalue <- sprintf(pvalue, fmt = '%#.3f')


  ### combine with P-value
  pvalue <- rbind(pvalue, matrix(rep("", 2 * (length(lvl) - 1)),
                                 ncol = 2))
  f <- data.frame(f, pvalue, stringsAsFactors = FALSE)
  names(f)[9:10] <- pvalue.name
  dummy <- do.call(c,
                   lapply(names(f), function(z) {
                     max(c(max(nchar(z), na.rm = TRUE),
                           max(nchar(f[, z]), na.rm = TRUE)), na.rm = TRUE)
                   })
  )

  ## combine dummy to f table
  dummy <- do.call(c, lapply(dummy, function(z) {
    paste0(rep("-", z), collapse = "")
  }))
  f <- rbind(f, dummy)

  ## combine total summ to f table
  dummy <- summ(NULL, x, rnd = rnd, print.table = FALSE)[, display]
  dummy <- c(dummy, "", "")
  names(dummy) <- names(f)
  f <- rbind(f, dummy)

  ## formatting row names
  nf <- nrow(f)
  row.names(f)[1:(nf-2)] <- lvl
  dummy <- paste0(rep("-", max(nchar(lvl), na.rm = TRUE)), collapse = "")
  row.names(f)[c(nf-1, nf)] <- c(dummy, x.name)

  if (print.table) {
    texts <- paste0("Number Summary: '", x.name, "' grouped by '",
                    by.name, "'", collapse = "")
    printText(f, texts)

    if (!is.null(attr(x, "label")) | !is.null(attr(by, "label"))) {
      printMsg("Labels:")
    }
    if (!is.null(attr(x, "label"))) {
      printMsg(paste0(x.name, ": ", attr(x, "label"), collapse = ""))
    }
    if (!is.null(attr(by, "label"))) {
      printMsg(paste0(by.name, ": ", attr(by, "label"), collapse = ""))
    }
  }

  invisible(f)
}

#' @rdname summBy
#' @export
summBy.list <- function(data = NULL, ... , by,
                        na.rm = FALSE, rnd = 1,
                        print.table = TRUE)
{
  arguments <- as.list(match.call())[-1]
  data <- data.frame(data)
  if (!is.null(data)) {
    by <- eval(substitute(by), data)
  }
  nonX <- c("data", "by", "row.pct", "na.rm", "rnd", "print.table")
  x.names <- arguments[!names(arguments) %in% nonX]
  by.name <- arguments[["by"]]


  hasColon <- grepl(":", as.character(x.names))
  if (any(hasColon) & !is.null(data)) {
    data <- data.frame(data)
    x.names <- do.call(
      c,
      lapply(as.character(x.names), function(z) {
        hasColon <- grepl(":", z)
        if (hasColon) {
          varsColonSplit(data, z, hasColon)
        } else {
          z
        }
      })
    )
    data <- data[, as.character(x.names)]
  } else if (!is.null(data)) {
    data <- data[, as.character(x.names)]
  } else {
    # restructure label of x
    if (any(grepl("\\$", x.names))) {
      varsNames <- do.call(
        c,
        lapply(x.names, function(z) {
          v <- as.character(z)
          v[3]
        })
      )
      x.lbl <- lapply(x.names, function(z) {
        v <- as.character(z)
        paste0(v[2], v[1], v[3], collapse = "")
      })
    }
    if (any(grepl("\\$", by.name))) {
      by.lbl <- as.character(by.name)
      by.lbl <- by.lbl[3]
      by.name <- by.lbl
    }
    data <- do.call(data.frame, x.names)
    names(data) <- varsNames
  }

  f <- do.call(
    rbind,
    lapply(names(data), function(z) {
      t <- data[, z]
      t <- summ(NULL, t, by = by, rnd = rnd, print.table = FALSE)
      rowNames <- row.names(t)
      rowNames[nrow(t)] <- z
      t <- data.frame("Levels" = rowNames, t,
                      stringsAsFactors = FALSE)
      v <- do.call(c,
                   lapply(t, function(z) {
                     v <- max(nchar(as.character(z)), na.rm = TRUE)
                     v <- paste0(rep("=", v), collapse = "")
                     v
                   })
      )
      t <- rbind(t, v)
      row.names(t) <- NULL
      t
    })
  )

  if (print.table) {
    texts <- paste0("Number Summary: '",
                    paste0(x.names, "'", collapse = ", "),
                    "\nby categories of: '", by.name,
                    "'", collapse = "")
    printText(f, texts, split = "by categories of: ",
              printDF = TRUE)

    x.lbl <- sapply(data, function(z) attr(z, "label"))
    by.lbl <- attr(by, "label")

    if (do.call(any,
                lapply(x.lbl, function(z) x.lbl != "NULL")) |
        !is.null(by.lbl)) {
      printMsg("labels:")
    }
    for (i in 1:length(x.names)) {
      if (!is.null(unlist(x.lbl[i]))) {
        printMsg(paste0(x.names[i], ": ", x.lbl[i], collapse = ""))
      }
    }
    if (!is.null(by.lbl))
      printMsg(paste0(by.name, ": ", by.lbl, collapse = ""))
  }

  invisible(f)
}

#' @rdname summBy
#' @export
summBy.data.frame <- function(data = NULL, ... , by,
                              na.rm = FALSE, rnd = 1,
                              print.table = TRUE)
{
  arguments <- as.list(match.call())
  vars <- names(data)
  by.name <- arguments$by
  by <- eval(substitute(by), data)
  type.numeric <- c("int", "double", "numeric")

  vars.type <- sapply(data, function(z)
    paste0(class(unlist(z)), collapse = ""))
  vars.names <- vars[(vars.type %in% type.numeric)]
  data <- data[, vars.names]

  if (is.data.frame(data)) {
    if (ncol(data) == 0)
      stop(" >>> no numeric variables found <<< ")

    names.invalid <- grep("^([[:alpha:]]|[.][._[:alpha:]])[._[:alnum:]]*$",
                          vars.names, value = TRUE, invert = TRUE)
    if (length(names.invalid) > 0) {
      vars.names[vars.names %in% names.invalid] <- paste0("v", names.invalid)
      names(data) <- vars.names
    }
  }

  if (is.data.frame(data)) {
    f <- do.call(
      rbind,
      lapply(names(data), function(z) {
        t <- data[, z]
        t <- summ(NULL, t, by = by, rnd = rnd,
                  print.table = FALSE)
        rowNames <- row.names(t)
        rowNames[nrow(t)] <- z
        t <- data.frame("Levels" = rowNames, t,
                        stringsAsFactors = FALSE)
        v <- do.call(
          c,
          lapply(t, function(z) {
            v <- max(nchar(as.character(z)), na.rm = TRUE)
            v <- paste0(rep("=", v), collapse = "")
            v
          })
        )
        t <- rbind(t, v)
        row.names(t) <- NULL
        t
      })
    )
    x.lbl <- lapply(data, function(z) attr(z, "label"))
  } else {
    f <- summBy.numeric(NULL, data, by, rnd = rnd,
                        print.table = FALSE)
    row.names(f)[nrow(f)] <- vars.names
    x.lbl <- attr(data, "label")
  }

  if (print.table) {
    texts <- paste0("Number Summary: '",
                    paste0(vars.names, "'", collapse = ", "),
                    "\nby categories of: '", by.name,
                    "'", collapse = "")
    printText(f, texts, printDF = TRUE)

    by.lbl <- attr(by, "label")

    if (do.call(any,
                lapply(x.lbl, function(z) x.lbl != "NULL")) |
        !is.null(by.lbl)) {
      printMsg("labels:")
    }
    for (i in 1:length(vars.names)) {
      if (!is.null(unlist(x.lbl[i]))) {
        printMsg(paste0(vars.names[i], ": ", x.lbl[i], collapse = ""))
      }
    }
    if (!is.null(by.lbl))
      printMsg(paste0(by.name, ": ", by.lbl, collapse = ""))
  }

  invisible(f)
}
